### News API root
### https://localhost:7773/api/v1/news
###

### TopHeadlines -give only one parameter is enough ex: country => works
GET  https://localhost:7773/api/v1/news/topHeadlines?country=US
###

### Fetching cateogires.
GET https://localhost:7773/api/v1/news/categories
###